config/routes.rb
Rails.application.routes.draw do
root 'posts#index', as: 'home'

get 'about' => 'pages#about', as: 'about'

resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true,
	length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@heading = 'Страничка About!'
		@text = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@post = Post.all
	end

	def new
		@post = Post.new
	end

	def show
		@post = Post.find(params[:id])
	end

	def create
		# render plain: params[:post].inspect
		@post = Post.new(post_params)

		@post.save

	  	if @post.save
	  		redirect_to @post
	  else
	  		render 'new'
	  end

	end

	private def post_params
		params.require(:post).permit(:title, :body)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
		<%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-bold">Ruby App</h5>
    <nav class="my-2 my-md-0 mr-md-3">
      <span class="p-2 text-dark"><%= link_to "Главная страница", home_path %></span>
			<span class="p-2 text-dark"><%= link_to "Страница About", about_path %></span>
    </nav>
		<span class="p-2 text-dark"><%= link_to "Добавить статью", new_post_path %></span>
  </div>

	<div class="container">
	  <%= yield %>
	</div>
    
  </body>
</html>

app/views/pages/about.html.erb
<h4 style="margin-bottom: 5rem"><%= @heading %></h4>

<p><%= @text %></p>

app/views/posts/index.html.erb
<section>
  <h1>Главная страница</h1>
<% @post.each do |post| %>

<h3><%= post.title %></h3>
<p><%= post.body %></p>

<% end %>
</section>

app/views/posts/new.html.erb
<h2>Добавление нового поста</h2>
<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
	  <% @post.errors.full_messages.each do |msg| %>
		  <div class="alert alert-danger"><%= msg %></div>
	  <% end %>
	<% end %>
<p>
  Название<br>
	<%= f.text_field(:title, {:class => 'form-control'}) %>
</p>

<p>
  Текст статьи<br>
	<%= f.text_area(:body, {:class => 'form-control'}) %>
</p>

<p>
	<%= f.submit({:class => 'btn btn-success'}) %>
</p>

<% end %>

app/views/posts/show.html.erb
<h1><%= $post.title %></h1>
<p><%= $post.body %></p>